"""Install this project as a skill into an agent's skill root.

The repository is the source; a skill root is an install location, the way
`site-packages` differs from a checkout. This script is the step between them.

The whole project installs, because the whole project is the skill. That is not a
turn of phrase: SKILL.md tells the Agent to run `python -m ainative.session`, and
that program is what makes the instructions checkable rather than advisory. A
bundle carrying the prose without the engine would send the Agent to a command that
does not exist on a machine that has only the install.

What lands in the skill root is a copy, not a link, so the installed skill keeps
working when the checkout moves or disappears. Engine changes reach it by
reinstalling, which is what `--check` is for: it reports drift rather than repairing
it silently, because the installed copy is a build output and edits there are lost.
"""

from __future__ import annotations

import argparse
import filecmp
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
SKILL_MD = REPO_ROOT / "SKILL.md"

#: Copied into the skill root. Directories are walked recursively.
BUNDLE_DIRS = ("src", "guidance", "templates", "docs")

#: Copied from the repository root. Everything the engine or its instructions need
#: at run time; `pyproject.toml` is here so the installed copy can be pip-installed
#: on its own.
BUNDLE_FILES = (
    "SKILL.md",
    "AGENTS.md",
    "README.md",
    "pyproject.toml",
    "integrity_gate.py",
    "install_skill.py",
    "LICENSE",
)

#: Never copied. Build outputs and local state, not part of the skill.
EXCLUDED_DIRS = {
    ".git", ".github", ".venv", ".pytest_cache", ".ruff_cache", "__pycache__",
    "artifacts", ".agents", "node_modules", "dist", "build", "tests",
}
EXCLUDED_SUFFIXES = {".pyc", ".pyo"}
EXCLUDED_NAMES = {"uv.lock", ".gitignore", ".installed-from"}

#: Written into the installed copy so a reader can tell it is generated.
MARKER = ".installed-from"


def skill_name() -> str:
    """Return the skill name from SKILL.md's frontmatter.

    Read rather than hardcoded, so the directory and the declared name cannot drift
    apart: discovery resolves `<name>/SKILL.md`, and a mismatch means the skill is
    never found.
    """

    text = SKILL_MD.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise SystemExit("SKILL.md does not open with YAML frontmatter")
    frontmatter = text[4:text.index("\n---", 4)]
    match = re.search(r"^name:\s*(\S+)\s*$", frontmatter, re.MULTILINE)
    if match is None:
        raise SystemExit("SKILL.md declares no name")
    return match.group(1)


def revision() -> str:
    """Return the source revision, or a placeholder outside a Git checkout."""

    try:
        done = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=REPO_ROOT, capture_output=True, text=True, check=False,
            encoding="utf-8", errors="replace")
    except OSError:
        return "unknown"
    return done.stdout.strip() if done.returncode == 0 and done.stdout.strip() else "unknown"


def _excluded(path: Path) -> bool:
    if path.name in EXCLUDED_NAMES or path.suffix in EXCLUDED_SUFFIXES:
        return True
    return any(part in EXCLUDED_DIRS for part in path.relative_to(REPO_ROOT).parts)


def sources() -> list[tuple[Path, Path]]:
    """Return (source, relative destination) for every file that installs."""

    pairs: list[tuple[Path, Path]] = []

    for name in BUNDLE_FILES:
        source = REPO_ROOT / name
        if not source.is_file():
            raise SystemExit(f"the bundle names a file that is not there: {name}")
        pairs.append((source, Path(name)))

    for name in BUNDLE_DIRS:
        directory = REPO_ROOT / name
        if not directory.is_dir():
            raise SystemExit(f"the bundle names a directory that is not there: {name}")
        for path in sorted(directory.rglob("*")):
            if path.is_file() and not _excluded(path):
                pairs.append((path, path.relative_to(REPO_ROOT)))

    return pairs


def install(destination: Path) -> int:
    """Copy the project into the skill root, replacing any previous install."""

    target = destination / skill_name()
    if target.exists():
        shutil.rmtree(target)

    for source, relative in sources():
        to = target / relative
        to.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, to)

    (target / MARKER).write_text(
        f"source: {REPO_ROOT}\nrevision: {revision()}\n"
        "generated by install_skill.py -- edits here are overwritten on reinstall\n",
        encoding="utf-8")

    files = [p for p in target.rglob("*") if p.is_file() and p.name != MARKER]
    size = sum(p.stat().st_size for p in files)
    print(f"installed {skill_name()} -> {target}")
    print(f"  {len(files)} files, {size} bytes")
    print(f"  the engine installs from there with: pip install -e \"{target}\"")
    return 0


def check(destination: Path) -> int:
    """Report whether the installed copy matches the source."""

    target = destination / skill_name()
    if not target.is_dir():
        print(f"not installed: {target}")
        return 1

    differing: list[str] = []
    missing: list[str] = []
    for source, relative in sources():
        to = target / relative
        if not to.is_file():
            missing.append(relative.as_posix())
        elif not filecmp.cmp(source, to, shallow=False):
            differing.append(relative.as_posix())

    expected = {relative for _source, relative in sources()}
    installed = {
        p.relative_to(target) for p in target.rglob("*")
        if p.is_file() and p.name != MARKER
    }
    extra = sorted(p.as_posix() for p in installed - expected)

    if not (differing or missing or extra):
        print(f"{target} matches the source at {revision()}")
        return 0

    for label, entries in (("differs", differing), ("missing", missing),
                           ("not in the source", extra)):
        for entry in entries[:10]:
            print(f"  {label}: {entry}")
        if len(entries) > 10:
            print(f"  {label}: ... and {len(entries) - 10} more")
    print(f"\n{target} does not match the source; reinstall to refresh it")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dest", type=Path, default=Path.home() / ".agents" / "skills",
        help="the skill root to install into (default: ~/.agents/skills)")
    parser.add_argument(
        "--check", action="store_true",
        help="report whether the installed copy matches the source")
    args = parser.parse_args()

    destination = args.dest.expanduser().resolve()
    if args.check:
        return check(destination)

    destination.mkdir(parents=True, exist_ok=True)
    return install(destination)


if __name__ == "__main__":
    sys.exit(main())
